name: Build Action
on:
    push:
      tags:
        - "v*.*.*"
    pull_request:
jobs:
  build-bionic:
    runs-on: ubuntu-latest
    steps:
      - 
        name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: build
        # The bionic build is run with docker-run-action because standard GitHub actions
        # use node20 which can't run on bionic
        # ToDo: verify this will error out properly on failure
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image: ghcr.io/aphysci/gravity_base:bionic
          shell: bash
          options: -v ${{ github.workspace }}:/home/aps/git/gravity -u aps
          run: |
            echo $(cat /etc/lsb-release)
            cd ~/git/gravity
            ls -lh
            pwd
            mkdir build && cd build
            pwd
            cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -GNinja ..
            cmake --build . --target install --parallel
            ./install/bin/ServiceDirectory &
            ctest --verbose && mkdir output
            ln -sf ./install ./gravity && tar -czvhf ./output/gravity-$(cat ./install/VERSION.txt)-bionic_amd64.tar.gz ./gravity
            echo "tarball is: gravity-$(cat ./install/VERSION.txt)-bionic_amd64.tar.gz"
      - 
        name: upload
        uses: actions/upload-artifact@v4
        with:
          name: gravity-bionic
          path: ${{ github.workspace }}/build/output/*.tar.gz
  build-focal:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aphysci/gravity_base:focal
    steps:
      -
        name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: build
        run: |
          echo $(cat /etc/lsb-release)
          pwd
          git config --global --add safe.directory '*'
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -GNinja ..
          cmake --build . --target install --parallel
          ./install/bin/ServiceDirectory &
          ctest --verbose
          mkdir output
          ln -sf ./install ./gravity && tar -czvhf ./output/gravity-$(cat ./install/VERSION.txt)-focal_amd64.tar.gz ./gravity
          echo "tarball is: gravity-$(cat ./install/VERSION.txt)-focal_amd64.tar.gz"
      - 
        name: upload
        uses: actions/upload-artifact@v4
        with:
          name: gravity-focal
          path: ${{ github.workspace }}/build/output/*.tar.gz
  build-jammy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aphysci/gravity_base:jammy
    steps:
      -
        name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: build
        run: |
          echo $(cat /etc/lsb-release)
          pwd
          git config --global --add safe.directory '*'
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -GNinja ..
          cmake --build . --target install --parallel
          ./install/bin/ServiceDirectory &
          ctest --verbose
          mkdir output
          ln -sf ./install ./gravity && tar -czvhf ./output/gravity-$(cat ./install/VERSION.txt)-jammy_amd64.tar.gz ./gravity
          echo "tarball is: gravity-$(cat ./install/VERSION.txt)-jammy_amd64.tar.gz"
      - 
        name: upload
        uses: actions/upload-artifact@v4
        with:
          name: gravity-jammy
          path: ${{ github.workspace }}/build/output/*.tar.gz
  build-alma:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aphysci/gravity_base:alma
    steps:
      -
        name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: build
        run: |
          echo $(cat /etc/os-release)
          pwd
          git config --global --add safe.directory '*'
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -GNinja ..
          cmake --build . --target install --parallel
          ./install/bin/ServiceDirectory &
          ctest --test-dir gravity_external_examples-prefix/src/gravity_external_examples-build --verbose
          mkdir output
          ln -sf ./install ./gravity && tar -czvhf ./output/gravity-$(cat ./install/VERSION.txt)-alma_amd64.tar.gz ./gravity
          echo "tarball is: gravity-$(cat ./install/VERSION.txt)-alma_amd64.tar.gz"
      - 
        name: upload
        uses: actions/upload-artifact@v4
        with:
          name: gravity-alma
          path: ${{ github.workspace }}/build/output/*.tar.gz
  build-windows-2019:
    runs-on: windows-2019
    timeout-minutes: 60
    steps:
      - 
        name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Use a set working python version and VS-2019 as newer versions can't seem to load _gravity.pyd on Windows
      - 
        name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.7.9'
      - 
        name: build
        shell: cmd
        run: |
          python --version
          python -m pip install --upgrade setuptools six
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=gravity  -G"Visual Studio 16 2019" -A x64 ..
          cmake --build . --target install --config Release --parallel
          start /B install/bin/ServiceDirectory.exe
          echo "Ran Service Directory"
          ctest --test-dir gravity_external_examples-prefix/src/gravity_external_examples-build -C Release --verbose
      - 
        name: archive
        shell: bash
        run: |
          cd build
          mkdir output
          7z a -r ./output/gravity-$(cat ./gravity/VERSION.txt)-windows_x64.zip gravity/*
      - 
        name: upload
        uses: actions/upload-artifact@v4
        with:
          name: gravity-windows
          path: ${{ github.workspace }}/build/output/*.zip
