name: Build Action
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull Image
        run: docker pull ghcr.io/aphysci/gravity_base:bionic
  build-bionic:
    runs-on: ubuntu-latest
    needs: login
    container:
      image: ghcr.io/aphysci/gravity_base:bionic
    steps:
      -
        name: build
        shell: bash
        run: |
          echo $(cat /etc/lsb-release)
          echo pwd
          echo ${{github.workspace}}