name: Build Action
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  build-bionic:
    runs-on: ubuntu-latest
    steps:
      - 
        name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image: ghcr.io/aphysci/gravity_base:bionic
          shell: bash
          options: -v ${{ github.workspace }}:/home/aps/git/gravity -u aps
          run: |
            echo $(cat /etc/lsb-release)
            cd ~/git/gravity
            ls -lh
            pwd
            mkdir build && cd build
            pwd
            cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -GNinja ..
            cmake --build . --target install --parallel --verbose
            ln -sf ./install ./gravity && tar -czvhf /home/aps/git/gravity-$(cat ./install/VERSION.txt)-bionic_amd64.tar.gz ./gravity
            echo "tarball is: gravity-$(cat ./install/VERSION.txt)-bionic_amd64.tar.gz"
