name: Build Action
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  build-bionic:
    runs-on: ubuntu-latest
    steps:
      - 
        name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - 
        name: build
        uses: addnab/docker-run-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image: ghcr.io/aphysci/gravity_base:bionic
          shell: bash
          options: -v ${{ github.workspace }}:/home/aps/git/gravity -u aps
          run: |
            echo $(cat /etc/lsb-release)
            cd ~/git/gravity
            ls -lh
            pwd
            mkdir build && cd build
            pwd
            cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -GNinja ..
            cmake --build . --target install --parallel
            LD_LIBRARY_PATH=/home/aps/git/gravity/build/install/lib ./install/bin/ServiceDirectory &
            ctest --verbose
            mkdir output
            ln -sf ./install ./gravity && tar -czvhf ./output/gravity-$(cat ./install/VERSION.txt)-bionic_amd64.tar.gz ./gravity
            echo "tarball is: gravity-$(cat ./install/VERSION.txt)-bionic_amd64.tar.gz"
      - 
        name: upload
        uses: actions/upload-artifact@v4
        with:
          name: gravity-bionic
          path: ${{ github.workspace }}/build/output/*.tar.gz
  build-focal:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aphysci/gravity_base:focal
    steps:
      -
        name: clone
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      -
        name: build
        run: |
          echo $(cat /etc/lsb-release)
          pwd
          git config --global --add safe.directory '*'
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -GNinja ..
          cmake --build . --target install --parallel
          LD_LIBRARY_PATH=`pwd`/install/lib ./install/bin/ServiceDirectory &
          ctest --verbose
          mkdir output
          ln -sf ./install ./gravity && tar -czvhf ./output/gravity-$(cat ./install/VERSION.txt)-focal_amd64.tar.gz ./gravity
          echo "tarball is: gravity-$(cat ./install/VERSION.txt)-focal_amd64.tar.gz"
      - 
        name: upload
        uses: actions/upload-artifact@v4
        with:
          name: gravity-focal
          path: ${{ github.workspace }}/build/output/*.tar.gz
  build-jammy:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aphysci/gravity_base:jammy
    steps:
      -
        name: clone
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      -
        name: build
        run: |
          echo $(cat /etc/lsb-release)
          pwd
          git config --global --add safe.directory '*'
          mkdir build && cd build
          cmake -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release -GNinja ..
          cmake --build . --target install --parallel
          LD_LIBRARY_PATH=`pwd`/install/lib ./install/bin/ServiceDirectory &
          ctest --verbose
          mkdir output
          ln -sf ./install ./gravity && tar -czvhf ./output/gravity-$(cat ./install/VERSION.txt)-jammy_amd64.tar.gz ./gravity
          echo "tarball is: gravity-$(cat ./install/VERSION.txt)-jammy_amd64.tar.gz"
      - 
        name: upload
        uses: actions/upload-artifact@v4
        with:
          name: gravity-jammy
          path: ${{ github.workspace }}/build/output/*.tar.gz
      
