name: Build Action
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  build-bionic:
    runs-on: ubuntu-latest
    steps:
      - 
        name: clone
        uses: actions/checkout@v3
      - uses: addnab/docker-run-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image: ghcr.io/aphysci/gravity_base:bionic
          shell: bash
          options: -v ${{ github.workspace }}:/home/aps/git/gravity -u aps
          run: |
            echo $(cat /etc/lsb-release)
            cd ~/git/gravity
            ls -lh
            pwd
