name: Build Action
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  build-bionic:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aphysci/gravity_base:bionic
    steps:
      - 
        name: clone
        uses: actions/checkout@v2
      -
        name: build
        shell: bash
        run: |
          echo $(cat /etc/lsb-release)
          echo pwd
          echo ${{github.workspace}}