name: Build Action
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    # The job that will use the container image you just pushed to ghcr.io
    build-job-bionic:
        runs-on: ubuntu-latest
        container: 
          image: ghcr.io/aphysci/gravity_base:bionic
          steps:
            - name: build-bionic
              uses: actions/checkout@v4
              shell: bash
            run: |
                echo $(cat /etc/lsb_release)
                echo pwd
                echo ${{github.workspace}}