name: Build Action
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  build-bionic:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/aphysci/gravity_base:bionic
    steps:
      - name: Setup environment
        # Ubuntu 18.04 has a GLib version too old for nodejs20 or later,
        # so, in order to do the tests, we must allow to use an older version.
        # https://github.com/actions/checkout/issues/1590
        # In that thread, Flamefire proposed this same solution:
        # https://github.com/boostorg/nowide/commit/d4aa719f21149de8960247403435e9b794a01255
        run: |
          echo "GHA_USE_NODE_20=false" >> $GITHUB_ENV
          echo "ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION=true" >> $GITHUB_ENV
      - 
        name: clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
      -
        name: build
        shell: bash
        run: |
          echo $(cat /etc/lsb-release)
          echo pwd
          echo ${{github.workspace}}